name: app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  collection: ^1.18.0
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  intl: ^0.19.0
  tflite_flutter: ^0.11.0
  flutter_facebook_auth: ^7.1.1
  easy_localization: ^3.0.7
  flutter_phoenix: ^1.1.1
  flutter_signin_button: ^2.0.0
  dio: ^5.8.0+1
  dartz: ^0.10.1
  jwt_decoder: ^2.0.1
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "asset/Image/heart.png"

dependency_overrides:
  collection: ^1.19.1
  meta: ^1.16.0
flutter:
  uses-material-design: true

  assets:
    - asset/Image/
    - asset/model/model.tflite
    - asset/translations/
